# Updated : 2025.01.16
# Version : 1.1.2
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# https://github.com/Xinyuan-LilyGO/T-CAN485

substitutions:
  board_chip: "ESP32"
  board_name: "LilyGo T-CAN485"

packages:
  device_base: !include ../base/device_base.yaml
  device_base_wifi: !include ../base/device_base_wifi.yaml
  device_cpu_freq_240: !include board_options_cpu_freq_240_esp32.yaml
  board_rgb_led: !include board_options_rgb_led_status.yaml

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

logger:
  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"

uart:
  # UART 0 : uart used for ESP32 flashing and logs, can be released if necessary (tx_pin: 1, rx_pin: 3)
  # UART 1
  - id: uart_esp_1
    tx_pin: 22
    rx_pin: 21
    baud_rate: 115200
    rx_buffer_size: 512

canbus:
  # CANBUS NODE 1
  - platform: esp32_can
    id: canbus_node1
    tx_pin: 27
    rx_pin: 26
    can_id: 1
    bit_rate: 500kbps

# +--------------------------------------+
# | Inverter Heartbeat Light             |
# +--------------------------------------+

light:
  # https://esphome.io/components/light/esp32_rmt_led_strip
  # ESP Light used to see the inverter heartbeat
  # Internal : only specifying an id without a name will implicitly set this to true.
  - platform: esp32_rmt_led_strip
    id: esp_light
    rgb_order: GRB
    pin: 4
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    entity_category: config
    default_transition_length: 0ms

# +--------------------------------------+
# | LilyGo T-CAN485 related config       |
# +--------------------------------------+

output:
  # MAX13487E SHDN (enable RS485 chip)
  - platform: gpio
    id: RS485_SE
    pin:
      number: 19
      inverted: true # set HIGH level
  # MAX13487E RE (enable RS485 autodirection)
  - platform: gpio
    id: RS485_EN
    pin:
      number: 17
      inverted: true # set HIGH level
  # RS485 and CAN Boost power supply
  - platform: gpio
    id: CGQ_EN
    pin:
      number: 16
      inverted: true # set HIGH level
  # SN65HVD231DR RS PIN (CAN high speed mode)
  - platform: gpio
    id: CAN_SE
    pin:
      number: 23
      inverted: false # set LOW level
