# Updated : 2025.01.16
# Version : 1.1.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# https://github.com/Xinyuan-LilyGO/T-Connect

substitutions:
  board_chip: "ESP32-S3"
  board_name: "LilyGo T-Connect"

packages:
  device_base: !include ../base/device_base.yaml
  device_base_wifi: !include ../base/device_base_wifi.yaml
  device_cpu_freq_240: !include board_options_cpu_freq_240_esp32-s3.yaml
  board_rgb_led: !include board_options_rgb_led_status.yaml
  # psram: !include board_options_psram_settings.yaml

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB # ajust according to your ESP32-S3 version
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio             # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing

# PSRAM activation with default options
# psram:
#   mode: octal
#   speed: 80MHz

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  ap:

logger:
  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"
  hardware_uart: USB_SERIAL_JTAG

uart:
  # UART 0 : USB UART port used for ESP32 flashing and logs, can be released if necessary (tx_pin: 43, rx_pin: 44)
  # UART 1
  - id: uart_esp_1
    tx_pin: 4
    rx_pin: 5
    baud_rate: 115200
    rx_buffer_size: 512
  # UART 2
  - id: uart_esp_2
    tx_pin: 6
    rx_pin: 7
    baud_rate: 115200
    rx_buffer_size: 512
  # UART 3
  - id: uart_esp_3
    tx_pin: 17
    rx_pin: 18
    baud_rate: 115200
    rx_buffer_size: 512

canbus:
  # CANBUS NODE 1
  - platform: esp32_can
    id: canbus_node1
    tx_pin: 9 # to CAN board CTX
    rx_pin: 10 # to CAN board CRX (with 4.7K resistor except for SN65HVD230)
    can_id: 1
    bit_rate: 500kbps

# SPI for LED strip APA102
spi:
  - id: lilygo_spi_bus
    clk_pin: 3
    mosi_pin: 8

light:
  # https://esphome.io/components/light/spi_led_strip.html
  # ESP Light used to see the inverter heartbeat
  # LilyGo T-Connect: APA102 chip - using spi library, 4 leds, data-IO8, clock-IO3
  - platform: spi_led_strip
    spi_id: lilygo_spi_bus
    id: esp_light
    num_leds: 4
    data_rate: 1MHz #default 1Mhz
    entity_category: config
    default_transition_length: 0ms
