# Updated : 2025.01.16
# Version : 1.2.6
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  board_chip: "ESP32-S3"
  board_name: "DevKitC-1"

packages:
  device_base: !include ../base/device_base.yaml
  device_base_wifi: !include ../base/device_base_wifi.yaml
  device_cpu_freq_240: !include board_options_cpu_freq_240_esp32-s3.yaml
  board_rgb_led: !include board_options_rgb_led_status.yaml
  # psram_settings: !include board_options_psram_settings.yaml

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB # ajust according to your ESP32-S3 version
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio             # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing

# PSRAM activation with default options
# psram:
#   mode: octal
#   speed: 80MHz

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

logger:
  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"
  hardware_uart: UART0 # UART0 / USB_SERIAL_JTAG

uart:
  # UART 0 : USB UART port used for ESP32 flashing and logs, can be released if necessary (tx_pin: 43, rx_pin: 44)
  # UART 1
  - id: uart_esp_1
    tx_pin: 17
    rx_pin: 18
    baud_rate: 115200
    rx_buffer_size: 512
  # UART 2
  - id: uart_esp_2
    tx_pin: 15
    rx_pin: 16
    baud_rate: 115200
    rx_buffer_size: 512
  # UART 3
  - id: uart_esp_3
    tx_pin: 13
    rx_pin: 14
    baud_rate: 115200
    rx_buffer_size: 512

canbus:
  # CANBUS NODE 1
  - platform: esp32_can
    id: canbus_node1
    tx_pin: 38 # to CAN board CTX
    rx_pin: 39 # to CAN board CRX (with 4.7K resistor except for SN65HVD230)
    can_id: 1
    bit_rate: 500kbps

light:
  # https://esphome.io/components/light/esp32_rmt_led_strip
  # ESP Light used to see the inverter heartbeat
  # Internal : only specifying an id without a name will implicitly set this to true.
  - platform: esp32_rmt_led_strip
    id: esp_light
    # name: ${name} ESP32 Light
    rgb_order: GRB
    pin: 48
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    entity_category: config
    default_transition_length: 0ms
    # restore_mode: ALWAYS_ON
