# Updated : 2025.01.16
# Version : 1.2.6
# GitHub  : https://github.com/SeByDocKy/pvbrain2

substitutions:
  board_chip: "ESP32-S3"
  board_name: "PVbrain2"

packages:
  device_base: !include ../base/device_base.yaml
  device_base_wifi: !include ../base/device_base_wifi.yaml
  device_cpu_freq_240: !include board_options_cpu_freq_240_esp32-s3.yaml
  board_rgb_led: !include board_options_rgb_led_status.yaml
  # psram: !include board_options_psram_settings.yaml

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB # ajust according to your ESP32-S3 version
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio             # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing

# PSRAM activation with default options
# psram:
#   mode: octal
#   speed: 80MHz

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

logger:
  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"
  hardware_uart: UART0 # UART0 / USB_SERIAL_JTAG

light:
  # https://esphome.io/components/light/status_led
  - platform: status_led
    name: ${name}_led_light_1
    id: led_light_1
    pin: 1
    entity_category: config

  - platform: status_led
    name: ${name}_led_light_2
    id: led_light_2
    pin: 2
    entity_category: config

  # https://esphome.io/components/light/esp32_rmt_led_strip
  - platform: esp32_rmt_led_strip
    name: ${name}_on_board_light_io48
    id: esp_light
    rgb_order: GRB
    pin: 48
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    entity_category: config
    default_transition_length: 0ms
